version: '3.7'

services:
  redis-queue:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "6379:6379"
    networks:
      - app-network

  users-api:
    image: users-api:latest
    container_name: users-api
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=PRFT
    ports:
      - "8083:8083"
    depends_on:
      - redis-queue
    networks:
      - app-network

  auth-api:
    image: auth-api:latest
    container_name: auth-api
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=PRFT
    ports:
      - "8000:8000"
    depends_on:
      - users-api
    networks:
      - app-network

  todos-api:
    image: todos-api:latest
    container_name: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis-queue
    networks:
      - app-network

  log-message-processor:
    image: log-message-processor:latest
    container_name: log-message-processor
    environment:
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "3000:3000"
    depends_on:
      - redis-queue
    networks:
      - app-network

  frontend:
    image: frontend:latest
    container_name: frontend
    environment:
      - AUTH_API_ADDRESS http://auth-api:8000
      - TODOS_API_ADDRESS http://todos-api:8082
    ports:
      - "8000:8000"
    depends_on:
      - auth-api
      - todos-api
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge