name: Deploy Pipeline

on:
  workflow_run:
    workflows:
      - "Docker CI auth-api"
      - "Docker CI frontend"
      - "Docker CI log-message-processor"
      - "Docker CI todos-api"
      - "Docker CI users-api"
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Azure VM and run docker-compose
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            cd ~/microservice-app-example/
            git pull origin master
            sudo docker-compose pull
            sudo docker-compose up --build -dV